FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY packages/shared/package.json packages/shared/
COPY packages/webpack-config/package.json packages/webpack-config/
COPY apps/backend/package.json apps/backend/
COPY apps/host/package.json apps/host/
COPY apps/dashboard/package.json apps/dashboard/
COPY apps/medical/package.json apps/medical/

RUN npm install
